name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Install OpenSSL (libssl1.1) for .NET 5 compatibility
      - name: Install libssl1.1
        run: |
          sudo apt-get upda
